syntax = "proto3";

option csharp_namespace = "LTC.MovieService.Grpc";

package movie;

service MovieGrpc {
  rpc GetPaginatedMovies (GetPaginatedMoviesRequest) returns (GetPaginatedMoviesResponse);
  rpc GetMovieById (GetMovieByIdRequest) returns (MovieMessage);
  rpc GetAllGenres (Empty) returns (GenresResponse);
  rpc GetAllFormats (Empty) returns (FormatsResponse);
  rpc GetAllActors (Empty) returns (ActorsResponse);
  rpc GetAllStudios (Empty) returns (StudiosResponse);
}

message Empty {}

message GetMovieByIdRequest {
  string id = 1;
}

message GetPaginatedMoviesRequest {
  int32 skipCount = 1;
  int32 maxResultCount = 2;
  string sorting = 3;
  string filter = 4;
}

message MovieMessage {
  string id = 1;
  string studioId = 2;
  string ratingId = 3;
  string title = 4;
  string originalTitle = 5;
  int32 durationMins = 6;
  string releaseDate = 7;
  string premiereDate = 8;
  string status = 9;
  string description = 10;
  string posterUrl = 11;
  string trailerUrl = 12;
  string createdAt = 13;
  string updatedAt = 14;
}

message GetPaginatedMoviesResponse {
  int64 totalCount = 1;
  repeated MovieMessage items = 2;
}

message GenreMessage {
  string id = 1;
  string name = 2;
}

message GenresResponse {
  repeated GenreMessage items = 1;
}

message FormatMessage {
  string id = 1;
  string name = 2;
}

message FormatsResponse {
  repeated FormatMessage items = 1;
}

message ActorMessage {
  string id = 1;
  string name = 2;
  string bio = 3;
}

message ActorsResponse {
  repeated ActorMessage items = 1;
}

message StudioMessage {
  string id = 1;
  string name = 2;
}

message StudiosResponse {
  repeated StudioMessage items = 1;
}